config/routes.rb
Rails.application.routes.draw do

  root    'static_pages#home'
  get     'about'   =>  'static_pages#about'
  get     'signup'  =>  'users#new'
  get     'login'   =>  'sessions#new'
  post    'login'   =>  'sessions#create'
  delete  'logout'  =>  'sessions#destroy'
  get     'feed'    =>  'submissions#index'

  resources :users
  resources :comments,        only: [:create, :edit, :destroy, :update]
  resources :votes,           only: [:create, :destroy]
  resources :subreddits,      only: [:index, :new, :create, :destroy, :show],
                              path: "r" do
    resources :submissions,   only: [:new, :create, :destroy, :show], path: "comments"
  end
  resources :subscriptions,   only: [:create, :destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: :true
  belongs_to :user
  has_many :comments, as: :commentable
  default_scope -> { order(created_at: :desc ) }
  validates_presence_of :user_id
  validates_presence_of :commentable
  validates :content, presence: true, length: { minimum: 2, maximum: 5120 }

  accepts_nested_attributes_for :commentable
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user,  only: [:create, :edit, :destroy]
  before_action :correct_user,    only: [:edit, :destroy]

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.commentable_id = params[:commentable_id]
    @comment.commentable_type = params[:commentable_type]
    if @comment.save
      redirect_to subreddit_submission_path(subreddit_id: @comment.commentable.subreddit.name, id: @comment.commentable.id)
      flash[:success] = "Comment added!"
    else
      redirect_to subreddit_submission_path(subreddit_id: @comment.commentable.subreddit.name, id: @comment.commentable.id)
      flash[:danger] = "Comment could not be added! :("
    end
  end

  def edit
  end

  def update
    @comment = Comment.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to subreddit_submission_url(subreddit_id: @comment.commentable.subreddit.name,
                                    id: @comment.commentable.id)
                      flash[:success] = "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    submission = @comment.commentable
    @comment.destroy
    flash[:success] = "Comment deleted."
    redirect_to subreddit_submission_url(subreddit_id: submission.subreddit.name,
                                id: submission.id)
  end

  private
    def comment_params
      params.require(:comment).permit(:content)
    end

    def correct_user
      @comment = current_user.comments.find_by(id: params[:id])
      if @comment.nil?
        if !current_user.admin
          flash[:danger] = "You do not have permission to do that."
          redirect_to root_url
        end
        @comment = Comment.find(params[:id])
      end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<section class="comment_info">
  <h3>
    <%= link_to comment.user.username, user_path(comment.user) %>
    <%= time_ago_in_words(comment.created_at) %> ago
    <% if comment.created_at != comment.updated_at %>
      | edited <%= time_ago_in_words(comment.updated_at) %> ago
    <% end %>
    <% if current_user.admin? || current_user?(comment.user) %>
      | <%= link_to "edit", edit_comment_path(comment) %>
      | <%= link_to "delete", comment, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </h3>
  <section class="comment">
    <%= comment.content %>
  </section>
  <!-- TODO: Nested comments -->
  <!-- <%= link_to "reply", "" %> -->
</section>

app/views/comments/edit.html.erb
<% provide(:title, 'Edit comment') %>

<h1>Edit your comment</h1>
<%= render 'shared/comment_form', comment: @comment,
                                  commentable: @comment.commentable %>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>