config/routes.rb
Rails.application.routes.draw do

  root    'static_pages#home'
  get     'about'   =>  'static_pages#about'
  get     'signup'  =>  'users#new'
  get     'login'   =>  'sessions#new'
  post    'login'   =>  'sessions#create'
  delete  'logout'  =>  'sessions#destroy'
  get     'feed'    =>  'submissions#index'

  resources :users
  resources :comments,        only: [:create, :edit, :destroy, :update]
  resources :votes,           only: [:create, :destroy]
  resources :subreddits,      only: [:index, :new, :create, :destroy, :show],
                              path: "r" do
    resources :submissions,   only: [:new, :create, :destroy, :show], path: "comments"
  end
  resources :subscriptions,   only: [:create, :destroy]

end

app/views/shared/_comment_form.html.erb
<div class="comment-form">
  <%= form_for(comment) do |f| %>
  <%= render "shared/errors", object: f.object %>

  <%= f.label :content, class: "control-label" %>
  <%= f.text_area :content, class: "form-control" %>
  <%= hidden_field_tag :commentable_id, commentable.id %>
  <%= hidden_field_tag :commentable_type, commentable.class %>

  <%= f.submit "Post", class: "btn btn-primary" %>

  <% end %>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_submission_form.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= form_for(@submission, url: subreddit_submissions_path(params[:subreddit_id])) do |f| %>
      <%= render "shared/errors", object: f.object %>

      <%= f.label :title, class: "control-label" %>
      <%= f.text_field :title, class: "form-control" %>

      <%= f.fields_for(@link) do |builder| %>
        <%= builder.label :url, class: "control-label" %>
        <%= builder.text_field :url, class: "form-control" %>
      <% end %>

      <%= f.submit "Post", class: "btn btn-primary" %>

    <% end %>
  </div>
</div>

app/views/shared/_votes.html.erb
  <% voteClasses = voteButtonClasses(votable) %>
  <%= link_to "&#9650;".html_safe, votes_path( { upvote: true,
                                       votable_id: votable.id }),
                                       method: :post,
                                       remote: true,
                                       class: voteClasses[0] %>
  <br>
  <%= link_to "&#9660;".html_safe, votes_path( { upvote: false,
                                       votable_id: votable.id }),
                                       method: :post,
                                       remote: true,
                                       class: voteClasses[1] %>