config/routes.rb
Rails.application.routes.draw do

  root    'static_pages#home'
  get     'about'   =>  'static_pages#about'
  get     'signup'  =>  'users#new'
  get     'login'   =>  'sessions#new'
  post    'login'   =>  'sessions#create'
  delete  'logout'  =>  'sessions#destroy'
  get     'feed'    =>  'submissions#index'

  resources :users
  resources :comments,        only: [:create, :edit, :destroy, :update]
  resources :votes,           only: [:create, :destroy]
  resources :subreddits,      only: [:index, :new, :create, :destroy, :show],
                              path: "r" do
    resources :submissions,   only: [:new, :create, :destroy, :show], path: "comments"
  end
  resources :subscriptions,   only: [:create, :destroy]

end

app/models/subreddit.rb
class Subreddit < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name

  has_many :submissions
  has_many :subscriptions, dependent: :destroy
  has_many :users, through: :subscriptions
  belongs_to :moderator, class_name: "User"

  validates_uniqueness_of :name, case_sensitive: false
end

app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController
  before_action :set_subreddit, only: [:show, :edit, :update, :destroy]

  # GET /subreddits
  # GET /subreddits.json
  def index
    @subreddits = Subreddit.paginate(page: params[:page])
  end

  # GET /subreddits/1
  # GET /subreddits/1.json
  def show
    @submissions = @subreddit.submissions.paginate(page: params[:page])
  end

  # GET /subreddits/new
  def new
    @subreddit = current_user.created_subreddits.build if logged_in?
  end

  # GET /subreddits/1/edit
  def edit
  end

  # POST /subreddits
  # POST /subreddits.json
  def create
    @subreddit = current_user.created_subreddits.build(subreddit_params)

    respond_to do |format|
      if @subreddit.save
        format.html { redirect_to @subreddit
                      flash[:sucess] = "r/#{@subreddit.name} created." }
        format.json { render :show, status: :created, location: @subreddit }
        current_user.subscriptions.build(subreddit: @subreddit).save
      else
        format.html { render :new }
        format.json { render json: @subreddit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subreddits/1
  # DELETE /subreddits/1.json
  def destroy
    @subreddit.destroy
    respond_to do |format|
      format.html { redirect_to subreddits_url
                    flash[:success] = "r/#{@subreddit.name} was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subreddit
      @subreddit = Subreddit.find_by(name: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subreddit_params
      params.require(:subreddit).permit(:name, :moderator)
    end
end

app/helpers/subreddits_helper.rb
module SubredditsHelper
end

app/views/subreddits/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@subreddit) do |f| %>
      <%= render "shared/errors", object: f.object %>

      <%= f.label :name, class: "control-label" %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.submit "Create topic", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/subreddits/_subreddit.html.erb
<li><%= link_to "r/#{subreddit.name}", subreddit %></li>

app/views/subreddits/_subscribe.html.erb
<%= form_for(current_user.subscriptions.build,
                                    remote: true) do |f| %>
  <div><%= hidden_field_tag :subreddit_id, @subreddit.id %></div>
  <%= f.submit "Subscribe", class: "btn btn-primary" %>
<% end %>

app/views/subreddits/_subscription_form.html.erb
<div id="subscribe_form">
  <% if current_user.subscribed_to?(@subreddit) %>
    <%= render 'unsubscribe' %>
  <% else %>
    <%= render 'subscribe' %>
  <% end %>
</div>

app/views/subreddits/_unsubscribe.html.erb
<%= link_to "New post", new_subreddit_submission_path(@subreddit), class: "btn btn-primary" %>
<br><br>
<%= form_for(current_user.subscriptions.find_by(subreddit_id: @subreddit.id),
                                  html: { method: :delete },
                                  remote: true )  do |f| %>
  <%= f.submit "Unsubscribe", class: "btn btn-primary" %>
<% end %>

app/views/subreddits/index.html.erb
<% provide(:title, 'All subreddits') %>
<h1>All Topics</h1>

<ul class="subreddits">
  <%= render @subreddits %>
</ul>

<%= will_paginate %>

app/views/subreddits/new.html.erb
<% provide(:title, "New topic") %>

<h1>New topic</h1>

<%= render 'form' %>

app/views/subreddits/show.html.erb
<% provide(:title, "r/#{@subreddit.name}") %>
<div class="row">
  <aside class="col-md-2">
    <section id="subreddit_info">
      <h1>r/<%= @subreddit.name %></h1>
      <h3><span id="subscribers"><%= @subreddit.subscriptions.count %></span> subscribers</h3>
      <br>
      <%= render "subscription_form" %>
    </section>
  </aside>
  <aside class="col-md-10">
    <section id="subreddit_posts">
      <h1>Submissions to r/<%= @subreddit.name %></h1>
      <section class="submissions">
        <%= render @submissions %>
      </section>
      <%= will_paginate @submissions %>
    </section>
  </aside>
</div>