config/routes.rb
Rails.application.routes.draw do

  root    'static_pages#home'
  get     'about'   =>  'static_pages#about'
  get     'signup'  =>  'users#new'
  get     'login'   =>  'sessions#new'
  post    'login'   =>  'sessions#create'
  delete  'logout'  =>  'sessions#destroy'
  get     'feed'    =>  'submissions#index'

  resources :users
  resources :comments,        only: [:create, :edit, :destroy, :update]
  resources :votes,           only: [:create, :destroy]
  resources :subreddits,      only: [:index, :new, :create, :destroy, :show],
                              path: "r" do
    resources :submissions,   only: [:new, :create, :destroy, :show], path: "comments"
  end
  resources :subscriptions,   only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Bellbird by Gio.
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= image_tag("ls.jpg.png", :alt => "rss feed") %>
    <%= link_to full_title(), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              topics <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Topics", subreddits_path %></li>
              <li><%= link_to "New Topic", new_subreddit_path %></li>
              <li class="divider"></li>
              <%= render current_user.subreddits %>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.username %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all',
  'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>